### ISSUE TITLE
Small Hangout time not working

### ISSUE THREAD

**Issue by mstephan** [adrienjoly/hangout-timer#3]
While the Big version seems to be working still, I could not get the small version to work.

**Comment by adrienjoly** [comment]
Sorry, to read that, @mstephan.
I've not used Hangout-timer for a long time, so feel free to fork, fix and pull-request if you want :-)

**Comment by sabrinalove** [comment]
None of the timers work for me =(

**Comment by adrienjoly** [comment]
@sabrinalove and @mstephan, I'm uploading a demo video, so that you can follow the exact same steps on your computer and tell me at what point you're seeing a different behaviour.

I'll let you know as soon as the video is fully uploaded. (in a few minutes from now)

**Comment by adrienjoly** [comment]
@sabrinalove here is the demo video: https://www.youtube.com/watch?v=VKtM0je-CTs

can you try to follow the same exact steps (from http://hangout-timer-app.appspot.com/) and at what stage of the process you're experiencing something different, please?

**Comment by sabrinalove** [comment]
Thank you @adrienjoly! I tried on another machine and it works perfectly. I think the issue may have been with the webcam on the machine I originally tried it on.. Regardless, it works great for me now, thank you =)

**Comment by adrienjoly** [comment]
@sabrinalove Great to know that it's working on your other computer! Thanks! ^^
