### ISSUE TITLE
Python 2.5 is no longer available.

### ISSUE THREAD

**Issue by Modacity** [adrienjoly/hangout-timer#4]
http://hangout-timer-app.appspot.com/ link no longer works. Can you upgrade?

**Comment by adrienjoly** [comment]
Google Hangout does not longer supports 3rd-party plug-ins like Hangout Timer, since April 25th, 2017. Read more here: https://developers.google.com/+/hangouts/support-faq

=> I removed the link from the Github page of this project and will archive it.
